apiVersion: apps/v1
kind: Deployment
metadata:
  name: blvckauth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blvckauth-api
  template:
    metadata:
      labels:
        app: blvckauth-api
    spec:
      containers:
      - name: blvckauth-api
        image: blvckoutdev/blvckauth-api:latest
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          - name: "LOGGING__LOGLEVEL__DEFAULT"
            value: "Information"
          - name: "Database__ConnectionString"
            valueFrom:
              secretKeyRef:
                name: blvckauth-api
                key: Database__ConnectionString
          - name: "Database__SeedData"
            value: "false"
          - name: Jwt__Key
            valueFrom:
              secretKeyRef:
                name: blvckauth-api
                key: Jwt__Key
          - name: Jwt__Issuer
            valueFrom:
              secretKeyRef:
                name: blvckauth-api
                key: Jwt__Issuer
          - name: Jwt__Audience
            valueFrom:
              secretKeyRef:
                name: blvckauth-api
                key: Jwt__Audience
          - name: "Admin__Username"
            valueFrom:
              secretKeyRef:
                name: blvckauth-api
                key: Admin__Username
          - name: Admin__Password
            valueFrom:
              secretKeyRef:
                name: blvckauth-api
                key: Admin__Password